---


- hosts: all
  become: true
  tasks:

  - name: install apache2 packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      update_cache: yes
      state: latest
    when: ansible_distribution == "Ubuntu"
