---


- hosts: all
  become: true
  tasks:

  - name: install apache2 & php packages
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
      state: latest
